<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shiu-Ting Ling">
<meta name="dcterms.date" content="2025-10-21">

<title>Assignment 6 - Text Analytics using quanteda – UTD_SDAR</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./icon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1abae18f1c827df6b05c9ac6e085bdaa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">UTD_SDAR</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dataframed-review" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">DataFramed Review</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dataframed-review">    
        <li>
    <a class="dropdown-item" href="./DataFramed320.html">
 <span class="dropdown-text">#320 The Next Industrial Revolution is Industrial AI</span></a>
  </li>  
        <li class="dropdown-header">To be continued…</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">about</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sarahokra/UTD_SDAR"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./DC_assignment01.html">EPPS6302</a></li><li class="breadcrumb-item"><a href="./DC_assignment06.html">Assignment 6</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">EPPS6356</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DV_assignment08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 8</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">EPPS6354</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_assignment01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_assignment02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_assignment03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_assignment04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://www.canva.com/design/DAGgUhTSGi4/qcXAi5X5Adf-zrd3mwco2w/edit?utm_content=DAGgUhTSGi4&amp;utm_campaign=designshare&amp;utm_medium=link2&amp;utm_source=sharebutton" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Proposal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_assignment05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_assignment06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_assignment07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_Progress02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Progress Presentation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IM_Final.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Presentation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">EPPS6302</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DC_assignment01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DC_assignment02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DC_assignment03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DC_assignment04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DC_assignment05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DC_assignment06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Assignment 6</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">My Implementation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TWBC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Female Breast Cancer in Taiwan</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">To be continued...</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#read-about-the-package-quanteda-at-httpsquanteda.io" id="toc-read-about-the-package-quanteda-at-httpsquanteda.io" class="nav-link active" data-scroll-target="#read-about-the-package-quanteda-at-httpsquanteda.io"><code>1.</code> Read about the package quanteda at https://quanteda.io/</a></li>
  <li><a href="#download-quanteda_textanalytics01.r-and-quanteda_textanalytics02.r-from-teams" id="toc-download-quanteda_textanalytics01.r-and-quanteda_textanalytics02.r-from-teams" class="nav-link" data-scroll-target="#download-quanteda_textanalytics01.r-and-quanteda_textanalytics02.r-from-teams"><code>2.</code> Download quanteda_textanalytics01.R and quanteda_textanalytics02.R from Teams</a></li>
  <li><a href="#analyze" id="toc-analyze" class="nav-link" data-scroll-target="#analyze"><code>3.</code> Analyze:</a>
  <ul class="collapse">
  <li><a href="#a.-biden-xi-summit-data" id="toc-a.-biden-xi-summit-data" class="nav-link" data-scroll-target="#a.-biden-xi-summit-data"><code>a.</code> Biden-Xi summit data</a>
  <ul class="collapse">
  <li><a href="#top-hashtags" id="toc-top-hashtags" class="nav-link" data-scroll-target="#top-hashtags">Top Hashtags</a></li>
  <li><a href="#hashtag-network-analysis-blue-network" id="toc-hashtag-network-analysis-blue-network" class="nav-link" data-scroll-target="#hashtag-network-analysis-blue-network">Hashtag Network Analysis (Blue Network)</a></li>
  <li><a href="#user-network-analysis-red-network" id="toc-user-network-analysis-red-network" class="nav-link" data-scroll-target="#user-network-analysis-red-network">User Network Analysis (Red Network)</a></li>
  </ul></li>
  <li><a href="#b.-us-presidential-inaugural-speeches" id="toc-b.-us-presidential-inaugural-speeches" class="nav-link" data-scroll-target="#b.-us-presidential-inaugural-speeches"><code>b.</code> US presidential inaugural speeches</a>
  <ul class="collapse">
  <li><a href="#word-cloud-analysis-1789-1826" id="toc-word-cloud-analysis-1789-1826" class="nav-link" data-scroll-target="#word-cloud-analysis-1789-1826">Word Cloud Analysis (1789-1826)</a></li>
  <li><a href="#comparison-word-cloud-obama-bush-and-trump" id="toc-comparison-word-cloud-obama-bush-and-trump" class="nav-link" data-scroll-target="#comparison-word-cloud-obama-bush-and-trump">Comparison Word Cloud: Obama, Bush, and Trump</a></li>
  <li><a href="#colorful-word-cloud-1789-1826" id="toc-colorful-word-cloud-1789-1826" class="nav-link" data-scroll-target="#colorful-word-cloud-1789-1826">Colorful Word Cloud (1789-1826)</a></li>
  <li><a href="#lexical-dispersion-plot-american" id="toc-lexical-dispersion-plot-american" class="nav-link" data-scroll-target="#lexical-dispersion-plot-american">Lexical Dispersion Plot: “American”</a></li>
  <li><a href="#lexical-dispersion-plot-american-vs-people-vs-communist" id="toc-lexical-dispersion-plot-american-vs-people-vs-communist" class="nav-link" data-scroll-target="#lexical-dispersion-plot-american-vs-people-vs-communist">Lexical Dispersion Plot: “American” vs “People” vs “Communist”</a></li>
  <li><a href="#colored-lexical-dispersion-plot-american-blue-vs-people-red-vs-communist-green" id="toc-colored-lexical-dispersion-plot-american-blue-vs-people-red-vs-communist-green" class="nav-link" data-scroll-target="#colored-lexical-dispersion-plot-american-blue-vs-people-red-vs-communist-green">Colored Lexical Dispersion Plot: “American” (Blue) vs “People” (Red) vs “Communist” (Green)</a></li>
  <li><a href="#word-frequency-plot-top-100-words-1789-1826" id="toc-word-frequency-plot-top-100-words-1789-1826" class="nav-link" data-scroll-target="#word-frequency-plot-top-100-words-1789-1826">Word Frequency Plot (Top 100 Words, 1789-1826)</a></li>
  <li><a href="#frequency-of-american-by-president-1949-2025" id="toc-frequency-of-american-by-president-1949-2025" class="nav-link" data-scroll-target="#frequency-of-american-by-president-1949-2025">Frequency of “American” by President (1949-2025)</a></li>
  <li><a href="#relative-frequency-of-american-by-president-1949-2025" id="toc-relative-frequency-of-american-by-president-1949-2025" class="nav-link" data-scroll-target="#relative-frequency-of-american-by-president-1949-2025">Relative Frequency of “American” by President (1949-2025)</a></li>
  <li><a href="#top-10-words-by-president-2001-2025" id="toc-top-10-words-by-president-2001-2025" class="nav-link" data-scroll-target="#top-10-words-by-president-2001-2025">Top 10 Words by President (2001-2025)</a></li>
  <li><a href="#keyness-analysis-trump-vs-obama" id="toc-keyness-analysis-trump-vs-obama" class="nav-link" data-scroll-target="#keyness-analysis-trump-vs-obama">Keyness Analysis: Trump vs Obama</a></li>
  <li><a href="#keyness-analysis-trumps-distinctive-words-only" id="toc-keyness-analysis-trumps-distinctive-words-only" class="nav-link" data-scroll-target="#keyness-analysis-trumps-distinctive-words-only">Keyness Analysis: Trump’s Distinctive Words Only</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#what-is-wordfish-do-research-on-quanteda-website" id="toc-what-is-wordfish-do-research-on-quanteda-website" class="nav-link" data-scroll-target="#what-is-wordfish-do-research-on-quanteda-website"><code>4.</code> What is Wordfish? (Do research on quanteda website)</a>
  <ul class="collapse">
  <li><a href="#what-is-wordfish" id="toc-what-is-wordfish" class="nav-link" data-scroll-target="#what-is-wordfish">What is Wordfish?</a></li>
  <li><a href="#practical-analysis---irish-budget-speeches-2010" id="toc-practical-analysis---irish-budget-speeches-2010" class="nav-link" data-scroll-target="#practical-analysis---irish-budget-speeches-2010">Practical Analysis - Irish Budget Speeches 2010</a>
  <ul class="collapse">
  <li><a href="#wordscores-model" id="toc-wordscores-model" class="nav-link" data-scroll-target="#wordscores-model">Wordscores Model</a></li>
  <li><a href="#wordscores-document-positions" id="toc-wordscores-document-positions" class="nav-link" data-scroll-target="#wordscores-document-positions">Wordscores Document Positions</a></li>
  <li><a href="#wordscores-with-lbg-transformation" id="toc-wordscores-with-lbg-transformation" class="nav-link" data-scroll-target="#wordscores-with-lbg-transformation">Wordscores with LBG Transformation</a></li>
  <li><a href="#wordfish-model" id="toc-wordfish-model" class="nav-link" data-scroll-target="#wordfish-model">Wordfish Model</a></li>
  <li><a href="#wordfish-document-positions" id="toc-wordfish-document-positions" class="nav-link" data-scroll-target="#wordfish-document-positions">Wordfish Document Positions</a></li>
  <li><a href="#correspondence-analysis" id="toc-correspondence-analysis" class="nav-link" data-scroll-target="#correspondence-analysis">Correspondence Analysis</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./DC_assignment01.html">EPPS6302</a></li><li class="breadcrumb-item"><a href="./DC_assignment06.html">Assignment 6</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Assignment 6 - Text Analytics using quanteda</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shiu-Ting Ling </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 21, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="read-about-the-package-quanteda-at-httpsquanteda.io" class="level1">
<h1><code>1.</code> Read about the package quanteda at https://quanteda.io/</h1>
<p>Done.</p>
</section>
<section id="download-quanteda_textanalytics01.r-and-quanteda_textanalytics02.r-from-teams" class="level1">
<h1><code>2.</code> Download quanteda_textanalytics01.R and quanteda_textanalytics02.R from Teams</h1>
<p>Done.</p>
</section>
<section id="analyze" class="level1">
<h1><code>3.</code> Analyze:</h1>
<section id="a.-biden-xi-summit-data" class="level2">
<h2 class="anchored" data-anchor-id="a.-biden-xi-summit-data"><code>a.</code> Biden-Xi summit data</h2>
<section id="top-hashtags" class="level3">
<h3 class="anchored" data-anchor-id="top-hashtags">Top Hashtags</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample program for using quanteda for text modeling and analysis</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Documentation: vignette("quickstart", package = "quanteda")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Website: https://quanteda.io/</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Package version: 4.3.1
Unicode version: 15.1
ICU version: 74.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Parallel computing: 8 of 8 threads used.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>See https://quanteda.io for tutorials and examples.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.textmodels)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.textplots)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Twitter data about President Biden and Xi summit in Novemeber 2021</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Do some background search/study on the event</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>summit <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/datageneration/datamethods/master/textanalytics/summit_11162021.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 14520 Columns: 90</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (50): screen_name, text, source, reply_to_screen_name, hashtags, symbol...
dbl  (26): user_id, status_id, display_text_width, reply_to_status_id, reply...
lgl  (10): is_quote, is_retweet, quote_count, reply_count, ext_media_type, q...
dttm  (4): created_at, quoted_created_at, retweet_created_at, account_create...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(summit)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>sum_twt <span class="ot">=</span> summit<span class="sc">$</span>text</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>toks <span class="ot">=</span> <span class="fu">tokens</span>(sum_twt)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>sumtwtdfm <span class="ot">&lt;-</span> <span class="fu">dfm</span>(toks)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(toks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "tokens"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Latent Semantic Analysis </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="do">## (https://quanteda.io/reference/textmodel_lsa.html)</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>sum_lsa <span class="ot">&lt;-</span> <span class="fu">textmodel_lsa</span>(sumtwtdfm, <span class="at">nd=</span><span class="dv">4</span>,  <span class="at">margin =</span> <span class="fu">c</span>(<span class="st">"both"</span>, <span class="st">"documents"</span>, <span class="st">"features"</span>))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sum_lsa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Length    Class     Mode   
sk                      4 -none-    numeric
docs                58080 -none-    numeric
features            63972 -none-    numeric
matrix_low_rank 232218360 -none-    numeric
data            232218360 dgCMatrix S4     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sum_lsa<span class="sc">$</span>docs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1]          [,2]          [,3]          [,4]
text1 8.678102e-03  9.529008e-03 -3.178574e-03  1.380732e-02
text2 8.676818e-06 -8.806186e-06 -5.989637e-06  1.677631e-05
text3 2.922127e-03  6.778967e-03  1.131673e-03 -3.176902e-03
text4 1.046624e-02  8.884054e-04 -4.282723e-03  4.960680e-03
text5 3.251208e-03  8.005843e-03  2.208204e-04 -4.656367e-03
text6 3.251208e-03  8.005843e-03  2.208204e-04 -4.656367e-03</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(sum_lsa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "textmodel_lsa"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tweet_dfm <span class="ot">&lt;-</span> <span class="fu">tokens</span>(sum_twt, <span class="at">remove_punct =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm</span>()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tweet_dfm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Document-feature matrix of: 6 documents, 15,927 features (99.89% sparse) and 0 docvars.
       features
docs    breaking news us president biden amp communist china leader xi
  text1        1    1  1         1     1   1         1     2      1  1
  text2        0    0  0         0     0   0         0     0      0  0
  text3        0    0  0         0     1   0         0     0      0  1
  text4        0    0  0         1     1   0         0     0      0  1
  text5        0    0  0         0     1   0         0     0      0  1
  text6        0    0  0         0     1   0         0     0      0  1
[ reached max_nfeat ... 15,917 more features ]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>tag_dfm <span class="ot">&lt;-</span> <span class="fu">dfm_select</span>(tweet_dfm, <span class="at">pattern =</span> <span class="st">"#*"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>toptag <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">topfeatures</span>(tag_dfm, <span class="dv">50</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(toptag, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "#china"       "#biden"       "#xijinping"   "#joebiden"    "#america"    
 [6] "#americans"   "#coronavirus" "#fentanyl"    "#xi"          "#us"         </code></pre>
</div>
</div>
<p>The most frequently used hashtags in the Biden-Xi summit Twitter data (<strong>Top 10</strong>):</p>
<ol type="1">
<li>#china</li>
<li>#biden</li>
<li>#xijinping</li>
<li>#joebiden</li>
<li>#america</li>
<li>#americans</li>
<li>#coronavirus</li>
<li>#fentanyl</li>
<li>#xi</li>
<li>#us</li>
</ol>
</section>
<section id="hashtag-network-analysis-blue-network" class="level3">
<h3 class="anchored" data-anchor-id="hashtag-network-analysis-blue-network">Hashtag Network Analysis (Blue Network)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"quanteda.textplots"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>tag_fcm <span class="ot">&lt;-</span> <span class="fu">fcm</span>(tag_dfm)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tag_fcm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Feature co-occurrence matrix of: 6 by 665 features.
               features
features        #breaking #breakingnews #biden #china #usa #pray4america
  #breaking             0             4      5      5    5             0
  #breakingnews         0             0      4      5    4             0
  #biden                0             0      0    443   49             0
  #china                0             0      0      8   76             0
  #usa                  0             0      0      0    6             0
  #pray4america         0             0      0      0    0             0
               features
features        #joebiden #xijinping #america #americans
  #breaking             0          0        0          0
  #breakingnews         0          0        0          0
  #biden              299        370      302        295
  #china              339        434      308        295
  #usa                 12         15        0          0
  #pray4america         0          0        0          0
[ reached max_nfeat ... 655 more features ]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>topgat_fcm <span class="ot">&lt;-</span> <span class="fu">fcm_select</span>(tag_fcm, <span class="at">pattern =</span> toptag)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_network</span>(topgat_fcm, <span class="at">min_freq =</span> <span class="dv">50</span>, <span class="at">edge_alpha =</span> <span class="fl">0.8</span>, <span class="at">edge_size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>The hashtag co-occurrence network reveals several key discussion clusters:</strong></p>
<ul>
<li><p><strong>Central cluster</strong>: #china, #biden, #xijinping, #joebiden, #america, and #americans form the core of the network, showing that most tweets discussed both leaders together.</p></li>
<li><p><strong>Health-related topics</strong>: #coronavirus and #fentanyl are closely connected to the main cluster, indicating that public health issues were important topics during the summit discussion.</p></li>
<li><p><strong>Human rights cluster</strong>: #uyghurs, #uyghurgenocide, #tibetans, #humanrights, and #xi form a separate cluster on the right side, showing that human rights concerns were a distinct theme in the Twitter conversation.</p></li>
<li><p><strong>Geopolitical topics</strong>: #taiwan, #usa, #us, and #ccp appear on the periphery, representing broader geopolitical discussions.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>user_dfm <span class="ot">&lt;-</span> <span class="fu">dfm_select</span>(tweet_dfm, <span class="at">pattern =</span> <span class="st">"@*"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>topuser <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">topfeatures</span>(user_dfm, <span class="dv">50</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(topuser, <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "@potus"           "@politico"        "@joebiden"        "@jendeben"       
 [5] "@eneskanter"      "@nwadhams"        "@phelimkine"      "@nahaltoosi"     
 [9] "@nba"             "@washwizards"     "@pelicansnba"     "@capitalonearena"
[13] "@kevinliptakcnn"  "@foxbusiness"     "@morningsmaria"   "@scmpnews"       
[17] "@petermartin_pcm" "@nytimes"         "@uyghur_american" "@kaylatausche"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>user_fcm <span class="ot">&lt;-</span> <span class="fu">fcm</span>(user_dfm)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(user_fcm, <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Feature co-occurrence matrix of: 20 by 711 features.
                 features
features          @youtube @bfmtv @cnn @lauhaim @barackobama @joebiden
  @youtube               0      0    0        0            0         0
  @bfmtv                 0      0    1        1            1         1
  @cnn                   0      0    0        1            1         1
  @lauhaim               0      0    0        0            1         1
  @barackobama           0      0    0        0            0         1
  @joebiden              0      0    0        0            0         3
  @kamalaharris          0      0    0        0            0         0
  @hillaryclinton        0      0    0        0            0         0
  @billclinton           0      0    0        0            0         0
  @cbsnews               0      0    0        0            0         0
                 features
features          @kamalaharris @hillaryclinton @billclinton @cbsnews
  @youtube                    0               0            0        0
  @bfmtv                      1               1            1        1
  @cnn                        1               1            1        1
  @lauhaim                    1               1            1        1
  @barackobama                1               1            1        1
  @joebiden                   1               1            1        1
  @kamalaharris               0               1            1        1
  @hillaryclinton             0               0            1        1
  @billclinton                0               0            0        1
  @cbsnews                    0               0            0        0
[ reached max_nfeat ... 10 more features, reached max_nfeat ... 701 more features ]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>user_fcm <span class="ot">&lt;-</span> <span class="fu">fcm_select</span>(user_fcm, <span class="at">pattern =</span> topuser)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_network</span>(user_fcm, <span class="at">min_freq =</span> <span class="dv">20</span>, <span class="at">edge_color =</span> <span class="st">"firebrick"</span>, <span class="at">edge_alpha =</span> <span class="fl">0.8</span>, <span class="at">edge_size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="user-network-analysis-red-network" class="level3">
<h3 class="anchored" data-anchor-id="user-network-analysis-red-network">User Network Analysis (Red Network)</h3>
<p>The user mention network shows several distinct groups:</p>
<ul>
<li><p><strong>NBA-related cluster</strong>: <span class="citation" data-cites="nba">@nba</span>, <span class="citation" data-cites="washwizards">@washwizards</span>, <span class="citation" data-cites="pelicansnba">@pelicansnba</span>, <span class="citation" data-cites="capitalonearena">@capitalonearena</span>, and <span class="citation" data-cites="eneskanter">@eneskanter</span> are closely connected. This is likely related to Enes Kanter (NBA player) who was vocal about China’s human rights issues.</p></li>
<li><p><strong>Journalists cluster</strong>: <span class="citation" data-cites="politico">@politico</span>, <span class="citation" data-cites="phelimkine">@phelimkine</span>, <span class="citation" data-cites="nahaltoosi">@nahaltoosi</span>, <span class="citation" data-cites="whnsc">@whnsc</span>, and <span class="citation" data-cites="anderscorr">@anderscorr</span> represent media and journalists covering the summit.</p></li>
<li><p><strong>Bloomberg reporters</strong>: <span class="citation" data-cites="nwadhams">@nwadhams</span>, <span class="citation" data-cites="jendeben">@jendeben</span>, and <span class="citation" data-cites="petermartin_pcm">@petermartin_pcm</span> form another journalist cluster.</p></li>
<li><p><strong>Wall Street Journal reporters</strong>: <span class="citation" data-cites="learyreports">@learyreports</span> and <span class="citation" data-cites="glubold">@glubold</span> form a separate cluster representing Wall Street Journal coverage of the summit.</p></li>
<li><p><strong>Other news professionals</strong>: <span class="citation" data-cites="betamoroney">@betamoroney</span>, <span class="citation" data-cites="evasmartai">@evasmartai</span>, and <span class="citation" data-cites="enilev">@enilev</span> represent other journalists and news professionals discussing the event.</p></li>
</ul>
</section>
</section>
<section id="b.-us-presidential-inaugural-speeches" class="level2">
<h2 class="anchored" data-anchor-id="b.-us-presidential-inaugural-speeches"><code>b.</code> US presidential inaugural speeches</h2>
<p><code>i.</code> Any similarities and differences over time and among presidents?</p>
<section id="word-cloud-analysis-1789-1826" class="level3">
<h3 class="anchored" data-anchor-id="word-cloud-analysis-1789-1826">Word Cloud Analysis (1789-1826)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample program for using quanteda for text modeling and analysis</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Documentation: vignette("quickstart", package = c("quanteda.textstats", "quanteda.textmodels")</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Website: https://quanteda.io/</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.textmodels)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.textplots)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Wordcloud</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co"># based on US presidential inaugural address texts, and metadata (for the corpus), from 1789 to present.</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>dfm_inaug <span class="ot">&lt;-</span> <span class="fu">corpus_subset</span>(data_corpus_inaugural, Year <span class="sc">&lt;=</span> <span class="dv">1826</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens</span>(<span class="at">remove_punct =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens_remove</span>(<span class="fu">stopwords</span>(<span class="st">'english'</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm_trim</span>(<span class="at">min_termfreq =</span> <span class="dv">10</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_wordcloud</span>(dfm_inaug)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This word cloud visualizes the most frequently used words in US presidential inaugural speeches from 1789 to 1826 (early presidents including Washington, Adams, Jefferson, Madison, Monroe, and John Quincy Adams).</p>
<p><strong>Most prominent words</strong> (largest size = highest frequency):</p>
<ul>
<li><strong>government</strong>: The most frequently used word, reflecting the focus on establishing and defining the new government system.</li>
<li><strong>people</strong>, <strong>states</strong>, <strong>country</strong>, <strong>united</strong>: Core concepts emphasizing national unity and the role of citizens.</li>
<li><strong>public</strong>, <strong>great</strong>, <strong>nation</strong>: Words highlighting the importance of public service and national identity.</li>
</ul>
<p><strong>Key themes identified</strong>:</p>
<ol type="1">
<li><p><strong>Governance and Constitution</strong>: “government”, “constitution”, “union”, “laws”, “powers”, “administration” - Early presidents emphasized the importance of constitutional governance.</p></li>
<li><p><strong>National Unity</strong>: “united”, “states”, “union”, “nation”, “country” - Reflecting the priority of keeping the young nation together.</p></li>
<li><p><strong>Civic Values</strong>: “people”, “citizens”, “public”, “rights”, “liberty”, “justice” - Emphasizing democratic ideals and citizen participation.</p></li>
<li><p><strong>Peace and Foreign Relations</strong>: “peace”, “war”, “foreign”, “nations”, “commerce” - Addressing both domestic stability and international relationships.</p></li>
<li><p><strong>Principles and Duties</strong>: “principles”, “duties”, “honor”, “trust”, “confidence” - Reflecting the moral language common in early American political discourse.</p></li>
</ol>
<p><strong>Note</strong>: This analysis only includes speeches up to 1826 (<code>Year &lt;= 1826</code>), representing the founding era of American democracy.</p>
</section>
<section id="comparison-word-cloud-obama-bush-and-trump" class="level3">
<h3 class="anchored" data-anchor-id="comparison-word-cloud-obama-bush-and-trump">Comparison Word Cloud: Obama, Bush, and Trump</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>inaug_speech <span class="ot">=</span> data_corpus_inaugural</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corpus_subset</span>(data_corpus_inaugural, </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>              President <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Trump"</span>, <span class="st">"Obama"</span>, <span class="st">"Bush"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens</span>(<span class="at">remove_punct =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens_remove</span>(<span class="fu">stopwords</span>(<span class="st">"english"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm</span>() <span class="sc">%&gt;%</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm_group</span>(<span class="at">groups =</span> President) <span class="sc">%&gt;%</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm_trim</span>(<span class="at">min_termfreq =</span> <span class="dv">5</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">textplot_wordcloud</span>(<span class="at">comparison =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This word cloud uses the <code>comparison = TRUE</code> parameter, where each word’s color indicates which president used that word with the <strong>highest relative frequency</strong> in their inaugural address.</p>
<p><strong>Obama (blue):</strong> - High-frequency words: “us”, “must”, “can”, “nation”, “people”, “generation”, “journey”, “common”, “oath” - Obama’s language emphasizes collective action (“us”, “must”), generational legacy (“generation”), and shared values (“common”, “journey”)</p>
<p><strong>Bush (light blue/cyan):</strong> - High-frequency words: “freedom”, “nation”, “america”, “liberty”, “free”, “hope”, “justice”, “story”, “history” - Bush’s speeches center on freedom as a core theme (“freedom”, “liberty”, “free”), along with historical narrative (“story”, “history”) and hope (“hope”)</p>
<p><strong>Trump (green):</strong> - High-frequency words: “america”, “thank”, “nation”, “country”, “back”, “never”, “government”, “bring” - Trump’s distinctive features include frequent use of “thank”, emphasis on restoration (“back”), and critical language toward government</p>
<p><strong>Note:</strong> Many words like “america”, “nation”, and “people” are commonly used by all three presidents, but are assigned to the president with the highest relative proportion.</p>
</section>
<section id="colorful-word-cloud-1789-1826" class="level3">
<h3 class="anchored" data-anchor-id="colorful-word-cloud-1789-1826">Colorful Word Cloud (1789-1826)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_wordcloud</span>(dfm_inaug, <span class="at">min_count =</span> <span class="dv">10</span>,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="fu">c</span>(<span class="st">'red'</span>, <span class="st">'pink'</span>, <span class="st">'green'</span>, <span class="st">'purple'</span>, <span class="st">'orange'</span>, <span class="st">'blue'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This word cloud displays the same data as the first word cloud (inaugural speeches from 1789-1826), but with multiple colors to enhance visual distinction between words. The colors are assigned randomly and do not represent different categories or presidents.</p>
<p><strong>Most prominent words</strong> (largest size = highest frequency):</p>
<ul>
<li><strong>government</strong> (purple): The dominant word, appearing most frequently in early presidential speeches.</li>
<li><strong>states</strong>, <strong>peace</strong>, <strong>war</strong> (red/orange): Key terms reflecting concerns about national unity and international relations.</li>
<li><strong>people</strong>, <strong>country</strong>, <strong>public</strong> (orange/red): Emphasizing democratic ideals and civic responsibility.</li>
<li><strong>great</strong>, <strong>every</strong>, <strong>us</strong>, <strong>may</strong> (yellow/orange): Common words used in political rhetoric.</li>
</ul>
<p><strong>Note</strong>: Unlike the comparison word cloud, this visualization uses <code>min_count = 10</code>, meaning only words appearing at least 10 times are displayed. The six colors (red, pink, green, purple, orange, blue) are used purely for visual variety, not to indicate any categorical distinction.</p>
</section>
<section id="lexical-dispersion-plot-american" class="level3">
<h3 class="anchored" data-anchor-id="lexical-dispersion-plot-american">Lexical Dispersion Plot: “American”</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>data_corpus_inaugural_subset <span class="ot">&lt;-</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">corpus_subset</span>(data_corpus_inaugural, Year <span class="sc">&gt;</span> <span class="dv">1949</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kwic</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset), <span class="at">pattern =</span> <span class="st">"american"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">textplot_xray</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This lexical dispersion plot (also called an x-ray plot) shows where the word “american” appears within each presidential inaugural speech from 1953 to 2025. Each vertical line represents one occurrence of the word, and the x-axis shows the relative position within the speech (0.00 = beginning, 1.00 = end).</p>
<p><strong>How to read this plot</strong>:<br>
- Each row represents one inaugural speech (labeled by Year-President)<br>
- Vertical black lines indicate where “american” appears in the speech<br>
- More lines = more frequent use of the word<br>
- Spread of lines shows whether the word is used throughout or concentrated in certain parts</p>
<p><strong>Key observations</strong>:</p>
<p><strong>High frequency users</strong> (many vertical lines):<br>
- <strong>2025-Trump</strong>: 15 occurrences, distributed across the speech<br>
- <strong>2017-Trump</strong>: 12 occurrences, with concentration in the middle section<br>
- <strong>2021-Biden</strong>: 10 occurrences, spread throughout the speech<br>
- <strong>1997-Clinton</strong>: 8 occurrences, distributed from middle to end<br>
- <strong>1985-Reagan</strong>: 6 occurrences, spread across the speech</p>
<p><strong>Low frequency users</strong> (few vertical lines):<br>
- <strong>1953-Eisenhower</strong>: Only 1 occurrence<br>
- <strong>1977-Carter</strong>: 3 occurrences<br>
- <strong>1969-Nixon</strong> and <strong>1973-Nixon</strong>: 2 occurrences each</p>
<p><strong>Trend over time</strong>: More recent presidents (Clinton, Bush, Obama, Trump, Biden) tend to use “american” more frequently than earlier presidents (Eisenhower, Nixon, Carter), suggesting an increasing emphasis on American identity in modern political rhetoric.</p>
</section>
<section id="lexical-dispersion-plot-american-vs-people-vs-communist" class="level3">
<h3 class="anchored" data-anchor-id="lexical-dispersion-plot-american-vs-people-vs-communist">Lexical Dispersion Plot: “American” vs “People” vs “Communist”</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_xray</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kwic</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset), <span class="at">pattern =</span> <span class="st">"american"</span>),</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kwic</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset), <span class="at">pattern =</span> <span class="st">"people"</span>),</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kwic</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset), <span class="at">pattern =</span> <span class="st">"communist"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Lexical Dispersion Plot Interpretation</strong></p>
<p>This lexical dispersion plot compares the distribution of two words — “american” and “people” — across presidential inaugural speeches from 1953 to 2025. The plot is divided into two panels (left: “american”, right: “people”). Note: We also attempted to visualize “communist”, but this word does not appear in any of the inaugural speeches, so no panel is displayed for it.</p>
<p><strong>Key observations</strong>:</p>
<p><strong>“People” (right panel) — Most frequently used (164 total occurrences)</strong>:<br>
- Almost every president uses “people” multiple times throughout their speeches<br>
- High frequency users: 1985-Reagan (16), 1969-Nixon (14), 1993-Clinton (12), 1997-Clinton (11), 2013-Obama (11)<br>
- Low frequency users: 1961-Kennedy (1), 2001-Bush (1)<br>
- The word appears distributed across entire speeches, indicating it’s a fundamental term in presidential rhetoric</p>
<p><strong>“American” (left panel) — Moderate usage (87 total occurrences)</strong>:<br>
- Usage varies significantly between presidents<br>
- High frequency: 2025-Trump (15), 2017-Trump (12), 2021-Biden (10), 1997-Clinton (8)<br>
- Low frequency: 1953-Eisenhower (1), 1961-Kennedy (0), 1973-Nixon (2)<br>
- Modern presidents tend to use “american” more frequently than earlier ones</p>
<p><strong>Comparison insights</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Word</th>
<th>Total Occurrences</th>
<th>Average per Speech</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>people</td>
<td>164</td>
<td>~8.6</td>
</tr>
<tr class="even">
<td>american</td>
<td>87</td>
<td>~4.6</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation</strong>: “People” is a universal, high-frequency term across all presidents, while “american” shows an increasing trend over time, with recent presidents (Trump, Biden) using it more frequently than earlier ones (Eisenhower, Kennedy, Nixon).</p>
</section>
<section id="colored-lexical-dispersion-plot-american-blue-vs-people-red-vs-communist-green" class="level3">
<h3 class="anchored" data-anchor-id="colored-lexical-dispersion-plot-american-blue-vs-people-red-vs-communist-green">Colored Lexical Dispersion Plot: “American” (Blue) vs “People” (Red) vs “Communist” (Green)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Why is the "communist" plot missing?</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">textplot_xray</span>(</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kwic</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset), <span class="at">pattern =</span> <span class="st">"american"</span>),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kwic</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset), <span class="at">pattern =</span> <span class="st">"people"</span>),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kwic</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset), <span class="at">pattern =</span> <span class="st">"communist"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">color =</span> keyword) <span class="sc">+</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>, <span class="st">"green"</span>)) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot is the same analysis as the previous one, but with colors added for better visual distinction: “american” in blue, “people” in red, and “communist” in green.</p>
<p><strong>Why is the “communist” plot missing?</strong></p>
<p>The word “communist” does not appear in any presidential inaugural speech from 1953 to 2025. Even though the code includes <code>pattern = "communist"</code> with green color assigned, there are no green lines in the plot because:</p>
<ol type="1">
<li><strong>Inaugural speeches are ceremonial</strong>: Presidents focus on unity, hope, and positive vision rather than attacking adversaries</li>
<li><strong>Diplomatic language</strong>: Even during the Cold War, presidents avoided directly naming “communist” as it could escalate tensions</li>
<li><strong>Rhetorical strategy</strong>: Instead of negative terms, presidents use positive framing like “freedom” and “democracy”</li>
</ol>
<p><strong>Comparison: “American” (Blue) vs “People” (Red)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 44%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>“American” (Blue)</th>
<th>“People” (Red)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Frequency</td>
<td>Moderate, varies by president</td>
<td>High, consistent across all</td>
</tr>
<tr class="even">
<td>Distribution</td>
<td>Often clustered in specific sections</td>
<td>Spread throughout speeches</td>
</tr>
<tr class="odd">
<td>Trend</td>
<td>Increasing in modern speeches</td>
<td>Stable over time</td>
</tr>
</tbody>
</table>
<p><strong>Presidents with notable usage patterns</strong>:<br>
- 2025-Trump: Highest “american” usage (13), moderate “people” (8)<br>
- 2017-Trump: High “american” (11), balanced “people” (10)<br>
- 1985-Reagan: Highest “people” usage (16), moderate “american” (7)<br>
- 1997-Clinton: High usage of both terms (9 and 11)<br>
- 1969-Nixon: High “people” (14), low “american” (3)</p>
<p><strong>Key insight</strong>: The absence of “communist” (green) demonstrates that presidential inaugural addresses maintain a positive, unifying tone rather than identifying external enemies, even during periods of significant geopolitical tension.</p>
</section>
<section id="word-frequency-plot-top-100-words-1789-1826" class="level3">
<h3 class="anchored" data-anchor-id="word-frequency-plot-top-100-words-1789-1826">Word Frequency Plot (Top 100 Words, 1789-1826)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.textstats)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>features_dfm_inaug <span class="ot">&lt;-</span> <span class="fu">textstat_frequency</span>(dfm_inaug, <span class="at">n =</span> <span class="dv">100</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by reverse frequency order</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>features_dfm_inaug<span class="sc">$</span>feature <span class="ot">&lt;-</span> <span class="fu">with</span>(features_dfm_inaug, <span class="fu">reorder</span>(feature, <span class="sc">-</span>frequency))</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(features_dfm_inaug, <span class="fu">aes</span>(<span class="at">x =</span> feature, <span class="at">y =</span> frequency)) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This scatter plot displays the frequency of the top 100 most common words in presidential inaugural speeches from 1789 to 1826. Words are arranged from highest to lowest frequency (left to right).</p>
<p><strong>Distribution pattern</strong>:<br>
The plot shows a typical <strong>Zipf’s Law</strong> distribution — a small number of words appear very frequently, while most words appear relatively rarely. The curve drops steeply at first, then flattens out (long tail).</p>
<p><strong>Top frequency words</strong> (frequency &gt; 50):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>government</td>
<td>93</td>
</tr>
<tr class="even">
<td>2</td>
<td>may</td>
<td>69</td>
</tr>
<tr class="odd">
<td>2</td>
<td>great</td>
<td>69</td>
</tr>
<tr class="even">
<td>4</td>
<td>states</td>
<td>67</td>
</tr>
<tr class="odd">
<td>5</td>
<td>people</td>
<td>64</td>
</tr>
<tr class="even">
<td>6</td>
<td>public</td>
<td>60</td>
</tr>
<tr class="odd">
<td>7</td>
<td>every</td>
<td>59</td>
</tr>
<tr class="even">
<td>8</td>
<td>country</td>
<td>55</td>
</tr>
<tr class="odd">
<td>9</td>
<td>war</td>
<td>52</td>
</tr>
<tr class="even">
<td>10</td>
<td>united</td>
<td>48</td>
</tr>
</tbody>
</table>
<p><strong>Mid-frequency words</strong> (frequency 25-50):<br>
- us (47), can (46), union (46), citizens (45), peace (43), nation (41), nations (40)<br>
- shall (39), foreign (34), state (34), power (32), rights (32), constitution (31)<br>
- These represent important political and governance concepts</p>
<p><strong>Lower frequency words</strong> (frequency &lt; 25):<br>
- happiness (19), administration (17), liberty (16), executive (15), fellow-citizens (14), success (13)<br>
- More specific terms that appear less often but still significant</p>
<p><strong>Key insight</strong>: The dominance of “government” (93 occurrences) reflects the primary concern of early presidents: establishing and legitimizing the new federal government system. Words like “states” (67), “union” (46), and “constitution” (31) further emphasize the focus on national structure and unity during the founding era.</p>
</section>
<section id="frequency-of-american-by-president-1949-2025" class="level3">
<h3 class="anchored" data-anchor-id="frequency-of-american-by-president-1949-2025">Frequency of “American” by President (1949-2025)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get frequency grouped by president</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>freq_grouped <span class="ot">&lt;-</span> <span class="fu">textstat_frequency</span>(<span class="fu">dfm</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset)), </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">groups =</span> data_corpus_inaugural_subset<span class="sc">$</span>President)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the term "american"</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>freq_american <span class="ot">&lt;-</span> <span class="fu">subset</span>(freq_grouped, freq_grouped<span class="sc">$</span>feature <span class="sc">%in%</span> <span class="st">"american"</span>)  </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(freq_american, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> frequency)) <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>) <span class="sc">+</span> </span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows how many times each president used the word “american” in their inaugural speech(es). Note that some presidents served two terms and gave two inaugural addresses, which may affect their total count.</p>
<p><strong>Frequency ranking</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>President</th>
<th>Frequency</th>
<th>Observation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Trump</td>
<td>24</td>
<td>Highest usage</td>
</tr>
<tr class="even">
<td>Clinton</td>
<td>13</td>
<td>Second highest</td>
</tr>
<tr class="odd">
<td>Biden</td>
<td>9</td>
<td>Third highest</td>
</tr>
<tr class="even">
<td>Bush</td>
<td>8</td>
<td>(Two terms combined)</td>
</tr>
<tr class="odd">
<td>Obama</td>
<td>8</td>
<td>(Two terms combined)</td>
</tr>
<tr class="even">
<td>Reagan</td>
<td>8</td>
<td>(Two terms combined)</td>
</tr>
<tr class="odd">
<td>Johnson</td>
<td>6</td>
<td>Moderate usage</td>
</tr>
<tr class="even">
<td>Nixon</td>
<td>5</td>
<td>(Two terms combined)</td>
</tr>
<tr class="odd">
<td>Carter</td>
<td>3</td>
<td>Low usage</td>
</tr>
<tr class="even">
<td>Eisenhower</td>
<td>3</td>
<td>Low usage</td>
</tr>
</tbody>
</table>
<p><strong>Key observations</strong>:</p>
<ol type="1">
<li><p><strong>Trump used “american” most frequently</strong> (24 times), nearly double the second-highest user (Clinton with 13). This reflects his emphasis on American identity and nationalism in his inaugural rhetoric.</p></li>
<li><p><strong>Clinton ranks second</strong> (13 times), showing strong emphasis on American identity in his speeches.</p></li>
<li><p><strong>Bush, Obama, and Reagan tied</strong> at 8 occurrences each, despite all serving two terms with two inaugural addresses.</p></li>
<li><p><strong>Cold War era presidents</strong> (Eisenhower, Nixon, Carter) used “american” less frequently (3-5 times).</p></li>
<li><p><strong>General trend</strong>: More recent presidents (Trump, Clinton, Biden) tend to use “american” more frequently than earlier presidents (Eisenhower, Nixon, Carter).</p></li>
</ol>
<p><strong>Note</strong>: This analysis counts only the exact word “american” (case-insensitive). Related terms like “America”, “Americans”, or “America’s” are counted separately.</p>
</section>
<section id="relative-frequency-of-american-by-president-1949-2025" class="level3">
<h3 class="anchored" data-anchor-id="relative-frequency-of-american-by-president-1949-2025">Relative Frequency of “American” by President (1949-2025)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>dfm_rel_freq <span class="ot">&lt;-</span> <span class="fu">dfm_weight</span>(<span class="fu">dfm</span>(<span class="fu">tokens</span>(data_corpus_inaugural_subset)), <span class="at">scheme =</span> <span class="st">"prop"</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dfm_rel_freq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Document-feature matrix of: 6 documents, 4,625 features (86.44% sparse) and 4 docvars.
                 features
docs                      my    friends        ,    before          i
  1953-Eisenhower 0.14582574 0.14582574 4.593511 0.1822822 0.10936930
  1957-Eisenhower 0.20975354 0.10487677 6.345045 0.1573152 0.05243838
  1961-Kennedy    0.19467878 0.06489293 5.451006 0.1297859 0.32446463
  1965-Johnson    0.17543860 0.05847953 5.555556 0.2339181 0.87719298
  1969-Nixon      0.28973510 0          5.546358 0.1241722 0.86920530
  1973-Nixon      0.05012531 0.05012531 4.812030 0.2005013 0.60150376
                 features
docs                   begin      the expression       of     those
  1953-Eisenhower 0.03645643 6.234050 0.03645643 5.176814 0.1458257
  1957-Eisenhower 0          5.977976 0          5.034085 0.1573152
  1961-Kennedy    0.19467878 5.580792 0          4.218040 0.4542505
  1965-Johnson    0          4.502924 0          3.333333 0.1754386
  1969-Nixon      0          5.629139 0          3.890728 0.4552980
  1973-Nixon      0          4.160401 0          3.408521 0.3007519
[ reached max_nfeat ... 4,615 more features ]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>rel_freq <span class="ot">&lt;-</span> <span class="fu">textstat_frequency</span>(dfm_rel_freq, <span class="at">groups =</span> dfm_rel_freq<span class="sc">$</span>President)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the term "american"</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>rel_freq_american <span class="ot">&lt;-</span> <span class="fu">subset</span>(rel_freq, feature <span class="sc">%in%</span> <span class="st">"american"</span>)  </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rel_freq_american, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> frequency)) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>) <span class="sc">+</span> </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Relative frequency"</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the <strong>relative frequency</strong> (percentage of total words) of “american” in each president’s inaugural speech(es). Unlike the previous plot that showed raw counts, this controls for speech length — a fairer comparison since some speeches are longer than others.</p>
<p><strong>Why use relative frequency?</strong> - Raw frequency can be misleading: a longer speech naturally has more words - Relative frequency = (word count / total words) × 100 - This shows the <strong>proportion</strong> of the speech devoted to a particular word</p>
<p><strong>Relative frequency ranking</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>President</th>
<th>Relative Frequency (%)</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Trump</td>
<td>1.05%</td>
<td>Highest emphasis on “american”</td>
</tr>
<tr class="even">
<td>Clinton</td>
<td>0.59%</td>
<td>Second highest</td>
</tr>
<tr class="odd">
<td>Bush</td>
<td>0.38%</td>
<td>Strong emphasis</td>
</tr>
<tr class="even">
<td>Johnson</td>
<td>0.35%</td>
<td>Above average</td>
</tr>
<tr class="odd">
<td>Obama</td>
<td>0.33%</td>
<td>Above average</td>
</tr>
<tr class="even">
<td>Biden</td>
<td>0.33%</td>
<td>Above average</td>
</tr>
<tr class="odd">
<td>Reagan</td>
<td>0.28%</td>
<td>Moderate</td>
</tr>
<tr class="even">
<td>Nixon</td>
<td>0.22%</td>
<td>Below average</td>
</tr>
<tr class="odd">
<td>Carter</td>
<td>0.22%</td>
<td>Below average</td>
</tr>
<tr class="even">
<td>Eisenhower</td>
<td>0.14%</td>
<td>Lowest emphasis</td>
</tr>
</tbody>
</table>
<p><strong>Key observations</strong>:</p>
<ol type="1">
<li><p><strong>Trump ranks highest</strong> with 1.05%, nearly double the second-highest (Clinton at 0.59%). This confirms his strong emphasis on American identity and nationalism in his inaugural rhetoric.</p></li>
<li><p><strong>Clinton ranks second</strong> even after adjusting for speech length, confirming his emphasis on American identity.</p></li>
<li><p><strong>Bush moves up in ranking</strong>: His relative frequency (0.38%) is higher than some presidents with similar raw counts, meaning “american” made up a larger portion of his speeches.</p></li>
<li><p><strong>Eisenhower’s low usage is confirmed</strong>: Both raw and relative frequency show he rarely used “american” in his inaugural addresses (0.14%).</p></li>
<li><p><strong>Consistent pattern</strong>: The relative frequency ranking is similar to the raw frequency ranking, with Trump and Clinton at the top, and Eisenhower at the bottom.</p></li>
</ol>
<p><strong>Comparison with raw frequency</strong>: This relative measure confirms that Trump’s high usage of “american” is not simply due to longer speeches — he genuinely emphasized this word more than any other president in this dataset.</p>
</section>
<section id="top-10-words-by-president-2001-2025" class="level3">
<h3 class="anchored" data-anchor-id="top-10-words-by-president-2001-2025">Top 10 Words by President (2001-2025)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dfm_weight_pres <span class="ot">&lt;-</span> data_corpus_inaugural <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">corpus_subset</span>(Year <span class="sc">&gt;</span> <span class="dv">2000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens</span>(<span class="at">remove_punct =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens_remove</span>(<span class="fu">stopwords</span>(<span class="st">"english"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm</span>() <span class="sc">%&gt;%</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm_weight</span>(<span class="at">scheme =</span> <span class="st">"prop"</span>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate relative frequency by president</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>freq_weight <span class="ot">&lt;-</span> <span class="fu">textstat_frequency</span>(dfm_weight_pres, <span class="at">n =</span> <span class="dv">10</span>, </span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">groups =</span> dfm_weight_pres<span class="sc">$</span>President)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> freq_weight, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">nrow</span>(freq_weight)<span class="sc">:</span><span class="dv">1</span>, <span class="at">y =</span> frequency)) <span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> group, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">nrow</span>(freq_weight)<span class="sc">:</span><span class="dv">1</span>,</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> freq_weight<span class="sc">$</span>feature) <span class="sc">+</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Relative frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This faceted plot shows the top 10 most frequently used words (by relative frequency) for each of the four 21st-century presidents: Biden, Bush, Obama, and Trump. Stopwords (common words like “the”, “and”, “is”) have been removed.</p>
<p><strong>Biden’s Top Words</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Relative Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>us</td>
<td>0.024</td>
</tr>
<tr class="even">
<td>2</td>
<td>america</td>
<td>0.016</td>
</tr>
<tr class="odd">
<td>3</td>
<td>can</td>
<td>0.014</td>
</tr>
<tr class="even">
<td>4</td>
<td>one</td>
<td>0.013</td>
</tr>
<tr class="odd">
<td>5</td>
<td>nation</td>
<td>0.011</td>
</tr>
<tr class="even">
<td>6</td>
<td>must</td>
<td>0.009</td>
</tr>
<tr class="odd">
<td>6</td>
<td>democracy</td>
<td>0.009</td>
</tr>
<tr class="even">
<td>8</td>
<td>story</td>
<td>0.008</td>
</tr>
<tr class="odd">
<td>8</td>
<td>american</td>
<td>0.008</td>
</tr>
<tr class="even">
<td>8</td>
<td>people</td>
<td>0.008</td>
</tr>
</tbody>
</table>
<p><strong>Key themes</strong>: Unity (“us”, “one”), democracy, collective identity</p>
<hr>
<p><strong>Bush’s Top Words</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Relative Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>freedom</td>
<td>0.030</td>
</tr>
<tr class="even">
<td>2</td>
<td>america</td>
<td>0.022</td>
</tr>
<tr class="odd">
<td>3</td>
<td>country</td>
<td>0.019</td>
</tr>
<tr class="even">
<td>4</td>
<td>nation</td>
<td>0.019</td>
</tr>
<tr class="odd">
<td>5</td>
<td>every</td>
<td>0.017</td>
</tr>
<tr class="even">
<td>6</td>
<td>citizens</td>
<td>0.017</td>
</tr>
<tr class="odd">
<td>7</td>
<td>us</td>
<td>0.017</td>
</tr>
<tr class="even">
<td>8</td>
<td>liberty</td>
<td>0.016</td>
</tr>
<tr class="odd">
<td>9</td>
<td>can</td>
<td>0.014</td>
</tr>
<tr class="even">
<td>10</td>
<td>americans</td>
<td>0.014</td>
</tr>
</tbody>
</table>
<p><strong>Key themes</strong>: Freedom, liberty, citizenship — reflecting post-9/11 rhetoric</p>
<hr>
<p><strong>Obama’s Top Words</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Relative Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>us</td>
<td>0.040</td>
</tr>
<tr class="even">
<td>2</td>
<td>must</td>
<td>0.023</td>
</tr>
<tr class="odd">
<td>3</td>
<td>can</td>
<td>0.018</td>
</tr>
<tr class="even">
<td>4</td>
<td>people</td>
<td>0.017</td>
</tr>
<tr class="odd">
<td>5</td>
<td>nation</td>
<td>0.016</td>
</tr>
<tr class="even">
<td>6</td>
<td>new</td>
<td>0.015</td>
</tr>
<tr class="odd">
<td>7</td>
<td>time</td>
<td>0.015</td>
</tr>
<tr class="even">
<td>8</td>
<td>every</td>
<td>0.014</td>
</tr>
<tr class="odd">
<td>9</td>
<td>america</td>
<td>0.013</td>
</tr>
<tr class="even">
<td>10</td>
<td>now</td>
<td>0.010</td>
</tr>
</tbody>
</table>
<p><strong>Key themes</strong>: Collective action (“us”, “must”, “can”), change (“new”, “now”)</p>
<hr>
<p><strong>Trump’s Top Words</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Relative Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>america</td>
<td>0.038</td>
</tr>
<tr class="even">
<td>2</td>
<td>american</td>
<td>0.024</td>
</tr>
<tr class="odd">
<td>3</td>
<td>country</td>
<td>0.023</td>
</tr>
<tr class="even">
<td>4</td>
<td>nation</td>
<td>0.021</td>
</tr>
<tr class="odd">
<td>5</td>
<td>thank</td>
<td>0.020</td>
</tr>
<tr class="even">
<td>6</td>
<td>people</td>
<td>0.019</td>
</tr>
<tr class="odd">
<td>7</td>
<td>one</td>
<td>0.016</td>
</tr>
<tr class="even">
<td>8</td>
<td>every</td>
<td>0.016</td>
</tr>
<tr class="odd">
<td>9</td>
<td>world</td>
<td>0.015</td>
</tr>
<tr class="even">
<td>9</td>
<td>great</td>
<td>0.015</td>
</tr>
</tbody>
</table>
<p><strong>Key themes</strong>: National identity (“america”, “american”, “country”), greatness</p>
<hr>
<p><strong>Cross-President Comparison</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Theme</th>
<th>Biden</th>
<th>Bush</th>
<th>Obama</th>
<th>Trump</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Most used word</td>
<td>us</td>
<td>freedom</td>
<td>us</td>
<td>america</td>
</tr>
<tr class="even">
<td>National identity</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓✓ (strongest)</td>
</tr>
<tr class="odd">
<td>Freedom/Liberty</td>
<td>-</td>
<td>✓✓</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Unity (“us”)</td>
<td>✓✓</td>
<td>✓</td>
<td>✓✓</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Action words</td>
<td>can, must</td>
<td>can</td>
<td>must, can</td>
<td>-</td>
</tr>
</tbody>
</table>
<p><strong>Key insight</strong>: Each president’s word choices reflect their political messaging — Bush emphasized “freedom” (War on Terror era), Obama and Biden emphasized “us” (unity), and Trump emphasized “america/american” (America First).</p>
</section>
<section id="keyness-analysis-trump-vs-obama" class="level3">
<h3 class="anchored" data-anchor-id="keyness-analysis-trump-vs-obama">Keyness Analysis: Trump vs Obama</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Only select speeches by Obama and Trump</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>pres_corpus <span class="ot">&lt;-</span> <span class="fu">corpus_subset</span>(data_corpus_inaugural, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                             President <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Obama"</span>, <span class="st">"Trump"</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dfm grouped by president</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>pres_dfm <span class="ot">&lt;-</span> <span class="fu">tokens</span>(pres_corpus, <span class="at">remove_punct =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens_remove</span>(<span class="fu">stopwords</span>(<span class="st">"english"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens_group</span>(<span class="at">groups =</span> President) <span class="sc">%&gt;%</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dfm</span>()</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate keyness and determine Trump as target group</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>result_keyness <span class="ot">&lt;-</span> <span class="fu">textstat_keyness</span>(pres_dfm, <span class="at">target =</span> <span class="st">"Trump"</span>)</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot estimated word keyness</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_keyness</span>(result_keyness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This keyness plot compares the distinctive word usage between Trump (target, blue) and Obama (reference, gray). The chi-squared (χ²) statistic measures how significantly a word is associated with one president over the other.</p>
<p><strong>How to read this plot</strong>:</p>
<ul>
<li><strong>Positive chi² values (right/blue)</strong>: Words used significantly MORE by Trump than Obama</li>
<li><strong>Negative chi² values (left/gray)</strong>: Words used significantly MORE by Obama than Trump</li>
<li><strong>Larger bars</strong>: Stronger association with that president</li>
</ul>
<hr>
<p><strong>Trump’s Distinctive Words (Blue)</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Chi² Value</th>
<th>Trump</th>
<th>Obama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>thank</td>
<td>18.81</td>
<td>26</td>
<td>3</td>
</tr>
<tr class="even">
<td>2</td>
<td>back</td>
<td>11.21</td>
<td>16</td>
<td>2</td>
</tr>
<tr class="odd">
<td>3</td>
<td>america</td>
<td>10.22</td>
<td>36</td>
<td>14</td>
</tr>
<tr class="even">
<td>4</td>
<td>bring</td>
<td>8.55</td>
<td>11</td>
<td>1</td>
</tr>
<tr class="odd">
<td>5</td>
<td>american</td>
<td>8.37</td>
<td>24</td>
<td>8</td>
</tr>
<tr class="even">
<td>6</td>
<td>country</td>
<td>8.37</td>
<td>24</td>
<td>8</td>
</tr>
<tr class="odd">
<td>7</td>
<td>right</td>
<td>7.56</td>
<td>10</td>
<td>1</td>
</tr>
<tr class="even">
<td>8</td>
<td>great</td>
<td>7.47</td>
<td>16</td>
<td>4</td>
</tr>
<tr class="odd">
<td>9</td>
<td>president</td>
<td>7.36</td>
<td>14</td>
<td>3</td>
</tr>
<tr class="even">
<td>10</td>
<td>going</td>
<td>7.28</td>
<td>9</td>
<td>0</td>
</tr>
</tbody>
</table>
<p><strong>Trump’s rhetorical style</strong>: Direct, action-oriented, populist messaging with emphasis on restoration (“back”, “bring”) and national pride (“america”, “american”, “great”).</p>
<hr>
<p><strong>Obama’s Distinctive Words (Gray)</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Chi² Value</th>
<th>Trump</th>
<th>Obama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>us</td>
<td>-32.93</td>
<td>4</td>
<td>44</td>
</tr>
<tr class="even">
<td>2</td>
<td>must</td>
<td>-14.91</td>
<td>4</td>
<td>25</td>
</tr>
<tr class="odd">
<td>3</td>
<td>can</td>
<td>-12.31</td>
<td>3</td>
<td>20</td>
</tr>
<tr class="even">
<td>4</td>
<td>generation</td>
<td>-6.97</td>
<td>0</td>
<td>9</td>
</tr>
<tr class="odd">
<td>5</td>
<td>time</td>
<td>-5.58</td>
<td>5</td>
<td>16</td>
</tr>
<tr class="even">
<td>6</td>
<td>work</td>
<td>-5.20</td>
<td>2</td>
<td>10</td>
</tr>
<tr class="odd">
<td>7</td>
<td>less</td>
<td>-5.04</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="even">
<td>8</td>
<td>liberty</td>
<td>-5.04</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="odd">
<td>9</td>
<td>may</td>
<td>-5.04</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="even">
<td>10</td>
<td>journey</td>
<td>-4.78</td>
<td>1</td>
<td>9</td>
</tr>
</tbody>
</table>
<p><strong>Obama’s rhetorical style</strong>: Inclusive, aspirational language emphasizing collective action (“us”, “must”, “can”) and historical continuity (“generation”, “journey”).</p>
<hr>
<p><strong>Key Contrast</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 31%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Trump</th>
<th>Obama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Primary pronoun</td>
<td>-</td>
<td>“us” (χ² = -32.93, strongest)</td>
</tr>
<tr class="even">
<td>Core theme</td>
<td>Restoration (“back”, “great”)</td>
<td>Progress (“journey”, “generation”)</td>
</tr>
<tr class="odd">
<td>Tone</td>
<td>Direct, emphatic</td>
<td>Aspirational, inclusive</td>
</tr>
<tr class="even">
<td>Focus</td>
<td>National identity</td>
<td>Collective action</td>
</tr>
<tr class="odd">
<td>Top word</td>
<td>“thank” (χ² = 18.81)</td>
<td>“us” (χ² = -32.93)</td>
</tr>
</tbody>
</table>
<p><strong>Insight</strong>: The keyness analysis reveals fundamentally different rhetorical strategies — Trump’s “America First” nationalism versus Obama’s inclusive progressivism. The word “thank” being Trump’s most distinctive word is notable because expressions of gratitude are uncommon in traditional inaugural addresses, reflecting his more personal, campaign-style approach.</p>
</section>
<section id="keyness-analysis-trumps-distinctive-words-only" class="level3">
<h3 class="anchored" data-anchor-id="keyness-analysis-trumps-distinctive-words-only">Keyness Analysis: Trump’s Distinctive Words Only</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot without the reference text (in this case Obama)</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_keyness</span>(result_keyness, <span class="at">show_reference =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows only Trump’s distinctive words (without Obama’s reference words), making it easier to focus on what makes Trump’s inaugural speech(es) unique compared to Obama’s.</p>
<p><strong>Trump’s Most Distinctive Words (ranked by chi² value)</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Word</th>
<th>Chi² Value</th>
<th>Trump</th>
<th>Obama</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>thank</td>
<td>18.81</td>
<td>26</td>
<td>3</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>2</td>
<td>back</td>
<td>11.21</td>
<td>16</td>
<td>2</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>3</td>
<td>america</td>
<td>10.22</td>
<td>36</td>
<td>14</td>
<td>0.001</td>
</tr>
<tr class="even">
<td>4</td>
<td>bring</td>
<td>8.55</td>
<td>11</td>
<td>1</td>
<td>0.003</td>
</tr>
<tr class="odd">
<td>5</td>
<td>american</td>
<td>8.37</td>
<td>24</td>
<td>8</td>
<td>0.004</td>
</tr>
<tr class="even">
<td>6</td>
<td>country</td>
<td>8.37</td>
<td>24</td>
<td>8</td>
<td>0.004</td>
</tr>
<tr class="odd">
<td>7</td>
<td>right</td>
<td>7.56</td>
<td>10</td>
<td>1</td>
<td>0.006</td>
</tr>
<tr class="even">
<td>8</td>
<td>great</td>
<td>7.47</td>
<td>16</td>
<td>4</td>
<td>0.006</td>
</tr>
<tr class="odd">
<td>9</td>
<td>president</td>
<td>7.36</td>
<td>14</td>
<td>3</td>
<td>0.007</td>
</tr>
<tr class="even">
<td>10</td>
<td>going</td>
<td>7.28</td>
<td>9</td>
<td>0</td>
<td>0.007</td>
</tr>
</tbody>
</table>
<p><strong>Additional distinctive words</strong>:</p>
<ul>
<li><strong>never</strong> (χ² = 6.61), <strong>foreign</strong> (χ² = 6.27): Emphatic promises, international concerns</li>
<li><strong>dreams, first, millions</strong> (χ² = 5.27): Scale, priority, aspirational</li>
<li><strong>states</strong> (χ² = 4.74), <strong>many</strong> (χ² = 4.17): Governance references</li>
</ul>
<p><strong>Statistically significant words (p &lt; 0.05)</strong>: 17 words total, including: thank, back, america, bring, american, country, right, great, president, going, never, foreign, dreams, first, millions, states, many</p>
<hr>
<p><strong>Thematic clusters in Trump’s rhetoric</strong>:</p>
<ol type="1">
<li><strong>Restoration</strong>: “back”, “bring”, “great” — returning to a previous state</li>
<li><strong>National identity</strong>: “america”, “american”, “country” — strong patriotic emphasis</li>
<li><strong>Action/Promise</strong>: “going”, “never”, “first” — direct, emphatic commitments</li>
<li><strong>Gratitude</strong>: “thank” — acknowledging supporters (unusual in inaugural addresses)</li>
<li><strong>Scale</strong>: “millions”, “foreign”, “states” — emphasizing breadth of impact</li>
</ol>
<p><strong>Key insight</strong>: The word “thank” has the highest keyness score (χ² = 18.81), which is notable because expressions of gratitude are uncommon in traditional inaugural addresses. Trump used “thank” 26 times compared to Obama’s 3 times. This reflects Trump’s more personal, campaign-style approach to the ceremonial speech.</p>
</section>
</section>
</section>
<section id="what-is-wordfish-do-research-on-quanteda-website" class="level1">
<h1><code>4.</code> What is Wordfish? (Do research on quanteda website)</h1>
<section id="what-is-wordfish" class="level2">
<h2 class="anchored" data-anchor-id="what-is-wordfish">What is Wordfish?</h2>
<p>Wordfish is a method that <strong>automatically figures out political positions from text</strong> — you don’t need to tell the computer who’s left-wing or right-wing, it discovers this on its own by looking at word patterns.</p>
<p><strong>How does it work?</strong><br>
- It looks at what words each speaker uses and how often<br>
- Then it automatically places speakers on a political spectrum<br>
- Use more “government-side words” → placed on the right<br>
- Use more “opposition-side words” → placed on the left</p>
<p><strong>What does Wordfish calculate?</strong><br>
- <strong>θ (theta)</strong>: Each speaker’s political position (this is what we care about most)<br>
- <strong>β (beta)</strong>: Which side each word leans toward (positive = government, negative = opposition)<br>
- <strong>ψ (psi)</strong>: How common each word is overall</p>
<p><strong>Comparison of Three Text Scaling Methods</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Wordscores</th>
<th>Wordfish</th>
<th>CA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>In one sentence</strong></td>
<td>Teacher gives you the answer key, you grade based on it</td>
<td>Let the computer find patterns on its own</td>
<td>Simplify complex data into fewer dimensions</td>
</tr>
<tr class="even">
<td><strong>Type</strong></td>
<td>Supervised</td>
<td>Unsupervised</td>
<td>Unsupervised</td>
</tr>
<tr class="odd">
<td><strong>Need reference texts?</strong></td>
<td>Yes (must specify who is left/right first)</td>
<td>No</td>
<td>No</td>
</tr>
<tr class="even">
<td><strong>How it works</strong></td>
<td>Calculate based on known reference documents</td>
<td>Use statistical model to estimate automatically</td>
<td>Dimensionality reduction (like compressing 3D → 2D)</td>
</tr>
<tr class="odd">
<td><strong>Provides confidence intervals?</strong></td>
<td>Yes</td>
<td>Yes</td>
<td>No</td>
</tr>
<tr class="even">
<td><strong>Advantage</strong></td>
<td>Simple and easy to understand</td>
<td>No need to know the answer beforehand</td>
<td>Good for visualization</td>
</tr>
<tr class="odd">
<td><strong>Disadvantage</strong></td>
<td>Must have reference documents</td>
<td>Math is more complex</td>
<td>Can’t know how accurate the estimate is</td>
</tr>
</tbody>
</table>
<p><strong>When to Use Which Method?</strong></p>
<ul>
<li><strong>Wordscores</strong>: When you already know some documents’ positions (e.g., Party A = left, Party B = right) and want to estimate others<br>
</li>
<li><strong>Wordfish</strong>: When you don’t know who’s left or right, and want the computer to figure it out<br>
</li>
<li><strong>CA</strong>: When you want to explore data and visualize the overall distribution</li>
</ul>
</section>
<section id="practical-analysis---irish-budget-speeches-2010" class="level2">
<h2 class="anchored" data-anchor-id="practical-analysis---irish-budget-speeches-2010">Practical Analysis - Irish Budget Speeches 2010</h2>
<section id="wordscores-model" class="level3">
<h3 class="anchored" data-anchor-id="wordscores-model">Wordscores Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.textmodels)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Irish budget speeches from 2010 (data from quanteda.textmodels)</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform corpus to dfm</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(data_corpus_irishbudget2010, <span class="at">package =</span> <span class="st">"quanteda.textmodels"</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>ie_dfm <span class="ot">&lt;-</span> <span class="fu">dfm</span>(<span class="fu">tokens</span>(data_corpus_irishbudget2010))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Set reference scores</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>refscores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">4</span>), <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">8</span>))</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict Wordscores model</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>ws <span class="ot">&lt;-</span> <span class="fu">textmodel_wordscores</span>(ie_dfm, <span class="at">y =</span> refscores, <span class="at">smooth =</span> <span class="dv">1</span>)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot estimated word positions (highlight words and print them in red)</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_scale1d</span>(ws,</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>                 <span class="at">highlighted =</span> <span class="fu">c</span>(<span class="st">"minister"</span>, <span class="st">"have"</span>, <span class="st">"our"</span>, <span class="st">"budget"</span>), </span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>                 <span class="at">highlighted_color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What is Wordscores?</strong></p>
<p>Wordscores is a supervised text scaling method that:<br>
1. Uses reference texts with known positions (in this case: Cowen (FF) = 1, Kenny (FG) = -1)<br>
2. Assigns scores to each word based on how often it appears in reference texts<br>
3. Predicts positions of unknown texts based on their word usage</p>
<p><strong>How to read this plot</strong>:</p>
<ul>
<li><strong>X-axis (Word score)</strong>: Political position from -1 (opposition/Fine Gael) to +1 (government/Fianna Fáil)<br>
</li>
<li><strong>Y-axis (Log term frequency)</strong>: How often the word appears (higher = more frequent)<br>
</li>
<li><strong>Red highlighted words</strong>: Selected words of interest</li>
</ul>
<p><strong>Highlighted words analysis</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Word</th>
<th>Score</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>our</strong></td>
<td>0.69</td>
<td>Strongly associated with government rhetoric (inclusive, ownership language)</td>
</tr>
<tr class="even">
<td><strong>have</strong></td>
<td>0.15</td>
<td>Slightly government-leaning, neutral</td>
</tr>
<tr class="odd">
<td><strong>budget</strong></td>
<td>-0.15</td>
<td>Slightly opposition-leaning</td>
</tr>
<tr class="even">
<td><strong>minister</strong></td>
<td>-0.49</td>
<td>Associated with opposition (addressing/criticizing ministers)</td>
</tr>
</tbody>
</table>
<p><strong>Words most associated with Government (score close to +1)</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Word</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>economy</td>
<td>0.89</td>
</tr>
<tr class="even">
<td>2010</td>
<td>0.87</td>
</tr>
<tr class="odd">
<td>investment</td>
<td>0.86</td>
</tr>
<tr class="even">
<td>confidence</td>
<td>0.82</td>
</tr>
<tr class="odd">
<td>development</td>
<td>0.81</td>
</tr>
<tr class="even">
<td>employment</td>
<td>0.81</td>
</tr>
<tr class="odd">
<td>scheme</td>
<td>0.80</td>
</tr>
<tr class="even">
<td>future</td>
<td>0.80</td>
</tr>
<tr class="odd">
<td>measures</td>
<td>0.78</td>
</tr>
<tr class="even">
<td>support</td>
<td>0.78</td>
</tr>
</tbody>
</table>
<p><strong>Words most associated with Opposition (score close to -1)</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Word</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>taoiseach</td>
<td>-0.93</td>
</tr>
<tr class="even">
<td>he</td>
<td>-0.88</td>
</tr>
<tr class="odd">
<td>his</td>
<td>-0.85</td>
</tr>
<tr class="even">
<td>bank</td>
<td>-0.84</td>
</tr>
<tr class="odd">
<td>young</td>
<td>-0.82</td>
</tr>
<tr class="even">
<td>opportunity</td>
<td>-0.82</td>
</tr>
<tr class="odd">
<td>may</td>
<td>-0.77</td>
</tr>
<tr class="even">
<td>april</td>
<td>-0.72</td>
</tr>
<tr class="odd">
<td>said</td>
<td>-0.72</td>
</tr>
<tr class="even">
<td>hope</td>
<td>-0.72</td>
</tr>
</tbody>
</table>
<p><strong>Pattern observations</strong>:</p>
<ol type="1">
<li><p><strong>Common words cluster at center-top</strong>: Frequent words like “the”, “of”, “to”, “and” appear at the top center, as they’re used equally by both sides</p></li>
<li><p><strong>Government words focus on economy</strong>: Words like “economy”, “investment”, “development”, “employment” suggest positive economic framing</p></li>
<li><p><strong>Opposition words focus on criticism</strong>: Words like “taoiseach”, “he”, “his”, “bank” suggest direct criticism of government leadership and banking policy</p></li>
<li><p><strong>“our” vs “minister”</strong>:</p>
<ul>
<li>Government speakers use “our” (score = 0.69) — inclusive, ownership language<br>
</li>
<li>Opposition speakers address “minister” (score = -0.49) — accountability, criticism</li>
</ul></li>
</ol>
<p><strong>Key insight</strong>: The Wordscores model reveals that seemingly neutral words carry political weight. Government rhetoric emphasizes economic progress (“economy”, “investment”, “confidence”), while opposition rhetoric focuses on accountability and criticism (“taoiseach”, “bank”, “minister”) — patterns that reflect the dynamics of parliamentary debate during the 2010 Irish budget crisis.</p>
</section>
<section id="wordscores-document-positions" class="level3">
<h3 class="anchored" data-anchor-id="wordscores-document-positions">Wordscores Document Positions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predictions</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ws, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot estimated document positions and group by "party" variable</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_scale1d</span>(pred, <span class="at">margin =</span> <span class="st">"documents"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">groups =</span> <span class="fu">docvars</span>(data_corpus_irishbudget2010, <span class="st">"party"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the <strong>predicted political positions</strong> of each speaker in the 2010 Irish budget debate, grouped by their party affiliation. The positions are estimated using the Wordscores model based on the words each speaker used.</p>
<p><strong>How to read this plot</strong>:</p>
<ul>
<li><strong>X-axis (Document position)</strong>: Political scale from negative (opposition) to positive (government)</li>
<li><strong>Horizontal lines</strong>: Confidence intervals (uncertainty in the estimate)</li>
<li><strong>Dots</strong>: Estimated position for each speaker</li>
<li><strong>Panels</strong>: Grouped by party</li>
</ul>
<p><strong>Predicted positions by speaker</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Speaker</th>
<th>Party</th>
<th>Score</th>
<th>SE</th>
<th>Position</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cowen, Brian</td>
<td>FF</td>
<td>0.213</td>
<td>0.003</td>
<td>Most government</td>
</tr>
<tr class="even">
<td>Lenihan, Brian</td>
<td>FF</td>
<td>0.116</td>
<td>0.003</td>
<td>Government</td>
</tr>
<tr class="odd">
<td>Gormley, John</td>
<td>Green</td>
<td>0.086</td>
<td>0.009</td>
<td>Government (coalition)</td>
</tr>
<tr class="even">
<td>Cuffe, Ciaran</td>
<td>Green</td>
<td>0.072</td>
<td>0.009</td>
<td>Government (coalition)</td>
</tr>
<tr class="odd">
<td>Ryan, Eamon</td>
<td>Green</td>
<td>0.057</td>
<td>0.007</td>
<td>Government (coalition)</td>
</tr>
<tr class="even">
<td>Morgan, Arthur</td>
<td>SF</td>
<td>0.019</td>
<td>0.004</td>
<td>Near center</td>
</tr>
<tr class="odd">
<td>OCaolain, Caoimhghin</td>
<td>SF</td>
<td>0.017</td>
<td>0.005</td>
<td>Near center</td>
</tr>
<tr class="even">
<td>Gilmore, Eamon</td>
<td>LAB</td>
<td>0.014</td>
<td>0.005</td>
<td>Near center</td>
</tr>
<tr class="odd">
<td>Bruton, Richard</td>
<td>FG</td>
<td>0.003</td>
<td>0.004</td>
<td>Near center</td>
</tr>
<tr class="even">
<td>Burton, Joan</td>
<td>LAB</td>
<td>-0.005</td>
<td>0.004</td>
<td>Slight opposition</td>
</tr>
<tr class="odd">
<td>ODonnell, Kieran</td>
<td>FG</td>
<td>-0.008</td>
<td>0.006</td>
<td>Slight opposition</td>
</tr>
<tr class="even">
<td>Higgins, Michael</td>
<td>LAB</td>
<td>-0.019</td>
<td>0.008</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td>Quinn, Ruairi</td>
<td>LAB</td>
<td>-0.027</td>
<td>0.008</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Kenny, Enda</td>
<td>FG</td>
<td>-0.137</td>
<td>0.005</td>
<td>Most opposition</td>
</tr>
</tbody>
</table>
<p><strong>Party summary</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 34%">
<col style="width: 13%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Party</th>
<th>Average Score</th>
<th>Role</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>FF (Fianna Fáil)</strong></td>
<td>0.165</td>
<td>Government (ruling party)</td>
<td>Strongest pro-government language</td>
</tr>
<tr class="even">
<td><strong>Green</strong></td>
<td>0.071</td>
<td>Government (coalition partner)</td>
<td>Moderate pro-government language</td>
</tr>
<tr class="odd">
<td><strong>SF (Sinn Féin)</strong></td>
<td>0.018</td>
<td>Opposition</td>
<td>Near center, moderate rhetoric</td>
</tr>
<tr class="even">
<td><strong>LAB (Labour)</strong></td>
<td>-0.009</td>
<td>Opposition</td>
<td>Slightly opposition-leaning</td>
</tr>
<tr class="odd">
<td><strong>FG (Fine Gael)</strong></td>
<td>-0.047</td>
<td>Opposition</td>
<td>Most opposition-leaning overall</td>
</tr>
</tbody>
</table>
<p><strong>Key observations</strong>:</p>
<ol type="1">
<li><p><strong>FF (Fianna Fáil)</strong> — Governing party members (Cowen at 0.213, Lenihan at 0.116) are positioned furthest right, reflecting pro-government language defending the budget.</p></li>
<li><p><strong>Green Party</strong> — As coalition partners with FF, all three members (Gormley, Cuffe, Ryan) are positioned on the government side (0.057-0.086) but closer to center than FF, showing more moderate support.</p></li>
<li><p><strong>Fine Gael (FG)</strong> — Shows the most variation within a party:</p>
<ul>
<li>Kenny, Enda has the most negative position (-0.137), indicating strongest opposition rhetoric<br>
</li>
<li>Bruton, Richard (0.003) and ODonnell, Kieran (-0.008) are much closer to center</li>
</ul></li>
<li><p><strong>Labour (LAB)</strong> — Members spread from slightly positive (Gilmore at 0.014) to negative (Quinn at -0.027), indicating varied opposition stances.</p></li>
<li><p><strong>Sinn Féin (SF)</strong> — Both members cluster near zero (0.017-0.019), indicating moderate, centrist rhetoric despite being an opposition party.</p></li>
</ol>
<p><strong>Model validation</strong>: The Wordscores model successfully separates government speakers (FF, Green with positive scores) from opposition speakers (FG, LAB with negative or near-zero scores) based purely on word usage, demonstrating how language reflects political position.</p>
</section>
<section id="wordscores-with-lbg-transformation" class="level3">
<h3 class="anchored" data-anchor-id="wordscores-with-lbg-transformation">Wordscores with LBG Transformation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot estimated document positions using the LBG transformation and group by "party" variable</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>pred_lbg <span class="ot">&lt;-</span> <span class="fu">predict</span>(ws, <span class="at">se.fit =</span> <span class="cn">TRUE</span>, <span class="at">rescaling =</span> <span class="st">"lbg"</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_scale1d</span>(pred_lbg, <span class="at">margin =</span> <span class="st">"documents"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">groups =</span> <span class="fu">docvars</span>(data_corpus_irishbudget2010, <span class="st">"party"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the same Wordscores analysis as the previous plot, but with <strong>LBG (Laver, Benoit, Garry) transformation</strong> applied. This rescaling method adjusts the predicted positions to better reflect the true spread of political positions.</p>
<p><strong>What is LBG transformation?</strong></p>
<p>The LBG transformation addresses a known issue with Wordscores: raw predictions tend to cluster toward the center. The LBG rescaling: - Expands the scale to show greater differentiation - Makes positions more comparable to the original reference scores - Allows predictions to exceed the original reference range (-1 to +1)</p>
<p><strong>Predicted positions with LBG rescaling</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Speaker</th>
<th>Party</th>
<th>LBG Score</th>
<th>Position</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cowen, Brian</td>
<td>FF</td>
<td>3.27</td>
<td>Most pro-government</td>
</tr>
<tr class="even">
<td>Lenihan, Brian</td>
<td>FF</td>
<td>1.57</td>
<td>Pro-government</td>
</tr>
<tr class="odd">
<td>Gormley, John</td>
<td>Green</td>
<td>1.03</td>
<td>Government (coalition)</td>
</tr>
<tr class="even">
<td>Cuffe, Ciaran</td>
<td>Green</td>
<td>0.80</td>
<td>Government (coalition)</td>
</tr>
<tr class="odd">
<td>Ryan, Eamon</td>
<td>Green</td>
<td>0.52</td>
<td>Government (coalition)</td>
</tr>
<tr class="even">
<td>Morgan, Arthur</td>
<td>SF</td>
<td>-0.14</td>
<td>Mild opposition</td>
</tr>
<tr class="odd">
<td>OCaolain, Caoimhghin</td>
<td>SF</td>
<td>-0.18</td>
<td>Mild opposition</td>
</tr>
<tr class="even">
<td>Gilmore, Eamon</td>
<td>LAB</td>
<td>-0.23</td>
<td>Mild opposition</td>
</tr>
<tr class="odd">
<td>Bruton, Richard</td>
<td>FG</td>
<td>-0.42</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Burton, Joan</td>
<td>LAB</td>
<td>-0.56</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td>ODonnell, Kieran</td>
<td>FG</td>
<td>-0.62</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Higgins, Michael</td>
<td>LAB</td>
<td>-0.81</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td>Quinn, Ruairi</td>
<td>LAB</td>
<td>-0.96</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Kenny, Enda</td>
<td>FG</td>
<td>-2.88</td>
<td>Most opposition</td>
</tr>
</tbody>
</table>
<p><strong>Comparison: Raw vs LBG Transformation</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Aspect</th>
<th>Raw Wordscores (Previous)</th>
<th>LBG Transformation (This plot)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Scale range</td>
<td>-0.14 to +0.21</td>
<td>-2.88 to +3.27</td>
</tr>
<tr class="even">
<td>Differentiation</td>
<td>Compressed, subtle</td>
<td>Expanded, clearer</td>
</tr>
<tr class="odd">
<td>Confidence intervals</td>
<td>Narrow</td>
<td>Wider</td>
</tr>
<tr class="even">
<td>Interpretation</td>
<td>Harder to distinguish</td>
<td>Easier to distinguish</td>
</tr>
</tbody>
</table>
<p><strong>Party summary with LBG rescaling</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 20%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Party</th>
<th>Score Range</th>
<th>Average</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>FF (Fianna Fáil)</strong></td>
<td>+1.57 to +3.27</td>
<td>2.42</td>
<td>Strongly pro-government</td>
</tr>
<tr class="even">
<td><strong>Green</strong></td>
<td>+0.52 to +1.03</td>
<td>0.78</td>
<td>Moderate, coalition partner</td>
</tr>
<tr class="odd">
<td><strong>SF (Sinn Féin)</strong></td>
<td>-0.18 to -0.14</td>
<td>-0.16</td>
<td>Mild opposition</td>
</tr>
<tr class="even">
<td><strong>LAB (Labour)</strong></td>
<td>-0.96 to -0.23</td>
<td>-0.64</td>
<td>Moderate opposition</td>
</tr>
<tr class="odd">
<td><strong>FG (Fine Gael)</strong></td>
<td>-2.88 to -0.42</td>
<td>-1.31</td>
<td>Opposition (varies widely)</td>
</tr>
</tbody>
</table>
<p><strong>Key observations</strong>:</p>
<ol type="1">
<li><p><strong>Greater separation</strong>: The LBG transformation makes the gap between government (FF at +1.57 to +3.27) and opposition (FG at -2.88 to -0.42) much clearer.</p></li>
<li><p><strong>Cowen’s dominance</strong>: Brian Cowen (FF) has the highest score (+3.27), far exceeding the original reference score of +1, reflecting extremely strong pro-budget rhetoric.</p></li>
<li><p><strong>Kenny’s strong opposition</strong>: Enda Kenny (FG) shows the most extreme opposition position (-2.88), nearly three times the original reference score of -1, consistent with his role as opposition leader.</p></li>
<li><p><strong>Green Party as middle ground</strong>: All Green members (0.52 to 1.03) fall between the governing FF and zero, reflecting their position as coalition partners with more moderate language.</p></li>
<li><p><strong>Labour variation</strong>: LAB members range from -0.23 (Gilmore) to -0.96 (Quinn), showing varied levels of opposition rhetoric within the party.</p></li>
</ol>
<p><strong>When to use LBG transformation</strong>: Use LBG when you want to see the full spread of political positions, especially when raw Wordscores predictions are too compressed to interpret clearly. The LBG transformation better reveals speakers who are more extreme than the reference texts.</p>
</section>
<section id="wordfish-model" class="level3">
<h3 class="anchored" data-anchor-id="wordfish-model">Wordfish Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate Wordfish model</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"quanteda.textmodels"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>wf <span class="ot">&lt;-</span> <span class="fu">textmodel_wordfish</span>(<span class="fu">dfm</span>(<span class="fu">tokens</span>(data_corpus_irishbudget2010)), <span class="at">dir =</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">5</span>))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot estimated word positions</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_scale1d</span>(wf, <span class="at">margin =</span> <span class="st">"features"</span>, </span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">highlighted =</span> <span class="fu">c</span>(<span class="st">"government"</span>, <span class="st">"global"</span>, <span class="st">"children"</span>, </span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"bank"</span>, <span class="st">"economy"</span>, <span class="st">"the"</span>, <span class="st">"citizenship"</span>,</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"productivity"</span>, <span class="st">"deficit"</span>), </span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">highlighted_color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the results of a <strong>Wordfish</strong> model applied to the 2010 Irish budget speeches. Unlike Wordscores (supervised), Wordfish is an <strong>unsupervised</strong> text scaling method that estimates word and document positions simultaneously without requiring reference texts.</p>
<p><strong>What is Wordfish?</strong></p>
<p>Wordfish is a scaling model that:<br>
- Estimates political positions from word frequencies alone (no reference texts needed)<br>
- Assumes word usage follows a Poisson distribution<br>
- Produces two parameters for each word: <strong>beta</strong> (position) and <strong>psi</strong> (frequency)</p>
<p><strong>How to read this plot</strong>:</p>
<ul>
<li><strong>X-axis (Estimated beta)</strong>: Word’s political position (negative = opposition, positive = government)<br>
</li>
<li><strong>Y-axis (Estimated psi)</strong>: Word’s overall frequency (higher = more common)<br>
</li>
<li><strong>Red highlighted words</strong>: Selected words of interest</li>
</ul>
<p><strong>Highlighted words analysis</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Word</th>
<th>Beta (Position)</th>
<th>Psi (Frequency)</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>the</strong></td>
<td>~0.0</td>
<td>~4.5 (highest)</td>
<td>Neutral, most frequent word</td>
</tr>
<tr class="even">
<td><strong>government</strong></td>
<td>~0.0</td>
<td>~2.8</td>
<td>Central topic, used by all</td>
</tr>
<tr class="odd">
<td><strong>economy</strong></td>
<td>~0.3</td>
<td>~2.5</td>
<td>Slightly government-side</td>
</tr>
<tr class="even">
<td><strong>children</strong></td>
<td>~-0.5</td>
<td>~0.5</td>
<td>Slightly opposition-side</td>
</tr>
<tr class="odd">
<td><strong>deficit</strong></td>
<td>~0.8</td>
<td>~0.3</td>
<td>Government-side (defending budget)</td>
</tr>
<tr class="even">
<td><strong>bank</strong></td>
<td>~-1.5</td>
<td>~0.0</td>
<td>Opposition-side (criticizing banks)</td>
</tr>
<tr class="odd">
<td><strong>global</strong></td>
<td>~1.5</td>
<td>~-2.5</td>
<td>Government-side (global context)</td>
</tr>
<tr class="even">
<td><strong>citizenship</strong></td>
<td>~-3.5</td>
<td>~-3.0</td>
<td>Strong opposition (rare word)</td>
</tr>
<tr class="odd">
<td><strong>productivity</strong></td>
<td>~2.5</td>
<td>~-4.0</td>
<td>Strong government (rare word)</td>
</tr>
</tbody>
</table>
<p><strong>Pattern observations</strong>:</p>
<ol type="1">
<li><strong>Triangular shape</strong>: Common words cluster at top-center; rare words spread to extremes
<ul>
<li>Frequent neutral words (the, government) → top center<br>
</li>
<li>Rare partisan words → bottom left/right corners</li>
</ul></li>
<li><strong>Opposition words (left/negative beta)</strong>:
<ul>
<li>“bank”, “citizenship” — criticism of financial sector, social issues<br>
</li>
<li>Associated with opposition rhetoric</li>
</ul></li>
<li><strong>Government words (right/positive beta)</strong>:
<ul>
<li>“deficit”, “global”, “productivity” — economic justification language<br>
</li>
<li>Used to defend budget decisions</li>
</ul></li>
<li><strong>Neutral/shared words (center)</strong>:
<ul>
<li>“the”, “government”, “economy” — used equally by both sides</li>
</ul></li>
</ol>
<p><strong>Key insight</strong>: Wordfish reveals that politically charged, rare words carry the most discriminating power. Common words like “the” and “government” are neutral, while specific policy terms like “productivity” (government) and “citizenship” (opposition) mark distinct political positions.</p>
</section>
<section id="wordfish-document-positions" class="level3">
<h3 class="anchored" data-anchor-id="wordfish-document-positions">Wordfish Document Positions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot estimated document positions</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_scale1d</span>(wf, </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">margin =</span> <span class="st">"documents"</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">groups =</span> <span class="fu">docvars</span>(data_corpus_irishbudget2010, <span class="st">"party"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the <strong>estimated political positions (theta)</strong> of each speaker in the 2010 Irish budget debate using the Wordfish model. Unlike Wordscores, Wordfish estimates these positions without requiring reference texts.</p>
<p><strong>How to read this plot</strong>:</p>
<ul>
<li><strong>X-axis (Estimated theta)</strong>: Political position scale (negative = opposition, positive = government)</li>
<li><strong>Horizontal lines</strong>: Confidence intervals</li>
<li><strong>Dots</strong>: Estimated position for each speaker</li>
<li><strong>Panels</strong>: Grouped by party</li>
</ul>
<p><strong>Predicted positions by speaker</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Speaker</th>
<th>Party</th>
<th>Theta</th>
<th>SE</th>
<th>Position</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lenihan, Brian</td>
<td>FF</td>
<td>1.82</td>
<td>0.020</td>
<td>Most pro-government</td>
</tr>
<tr class="even">
<td>Cowen, Brian</td>
<td>FF</td>
<td>1.77</td>
<td>0.023</td>
<td>Pro-government</td>
</tr>
<tr class="odd">
<td>Gormley, John</td>
<td>Green</td>
<td>1.19</td>
<td>0.073</td>
<td>Government (coalition)</td>
</tr>
<tr class="even">
<td>Cuffe, Ciaran</td>
<td>Green</td>
<td>0.76</td>
<td>0.073</td>
<td>Government (coalition)</td>
</tr>
<tr class="odd">
<td>Ryan, Eamon</td>
<td>Green</td>
<td>0.19</td>
<td>0.063</td>
<td>Near center</td>
</tr>
<tr class="even">
<td>Morgan, Arthur</td>
<td>SF</td>
<td>-0.13</td>
<td>0.028</td>
<td>Mild opposition</td>
</tr>
<tr class="odd">
<td>OCaolain, Caoimhghin</td>
<td>SF</td>
<td>-0.19</td>
<td>0.036</td>
<td>Mild opposition</td>
</tr>
<tr class="even">
<td>ODonnell, Kieran</td>
<td>FG</td>
<td>-0.49</td>
<td>0.041</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td>Gilmore, Eamon</td>
<td>LAB</td>
<td>-0.56</td>
<td>0.029</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Bruton, Richard</td>
<td>FG</td>
<td>-0.60</td>
<td>0.028</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td>Kenny, Enda</td>
<td>FG</td>
<td>-0.72</td>
<td>0.026</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Quinn, Ruairi</td>
<td>LAB</td>
<td>-0.96</td>
<td>0.039</td>
<td>Strong opposition</td>
</tr>
<tr class="odd">
<td>Higgins, Michael</td>
<td>LAB</td>
<td>-0.97</td>
<td>0.038</td>
<td>Strong opposition</td>
</tr>
<tr class="even">
<td>Burton, Joan</td>
<td>LAB</td>
<td>-1.10</td>
<td>0.015</td>
<td>Most opposition</td>
</tr>
</tbody>
</table>
<p><strong>Party summary</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 37%">
<col style="width: 25%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Party</th>
<th>Theta Range</th>
<th>Average</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>FF (Fianna Fáil)</strong></td>
<td>+1.77 to +1.82</td>
<td>1.79</td>
<td>Government (ruling party)</td>
</tr>
<tr class="even">
<td><strong>Green</strong></td>
<td>+0.19 to +1.19</td>
<td>0.71</td>
<td>Government (coalition partner)</td>
</tr>
<tr class="odd">
<td><strong>SF (Sinn Féin)</strong></td>
<td>-0.19 to -0.13</td>
<td>-0.16</td>
<td>Mild opposition</td>
</tr>
<tr class="even">
<td><strong>FG (Fine Gael)</strong></td>
<td>-0.72 to -0.49</td>
<td>-0.60</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td><strong>LAB (Labour)</strong></td>
<td>-1.10 to -0.56</td>
<td>-0.90</td>
<td>Opposition (most negative)</td>
</tr>
</tbody>
</table>
<p><strong>Key observations</strong>:</p>
<ol type="1">
<li><p><strong>Clear government-opposition divide</strong>: Wordfish successfully separates FF (theta ~1.8) from opposition parties (theta &lt; 0) without any reference texts.</p></li>
<li><p><strong>FF positioned furthest right</strong>: Lenihan (1.82) and Cowen (1.77) show the strongest pro-government language, consistent with their roles as Finance Minister and Taoiseach.</p></li>
<li><p><strong>Green Party variation</strong>:</p>
<ul>
<li>Gormley (1.19) and Cuffe (0.76) align strongly with government coalition<br>
</li>
<li>Ryan (0.19) positioned much closer to center, suggesting more moderate language or internal party differences</li>
</ul></li>
<li><p><strong>Labour most oppositional</strong>: All Labour members show negative theta, with Burton (-1.10) showing the strongest opposition rhetoric, followed by Higgins (-0.97) and Quinn (-0.96).</p></li>
<li><p><strong>Sinn Féin near center</strong>: Both SF members (Morgan at -0.13, OCaolain at -0.19) cluster near zero, indicating more moderate or centrist rhetoric compared to FG and LAB.</p></li>
<li><p><strong>Fine Gael moderate opposition</strong>: FG members range from -0.49 to -0.72, positioned between SF and LAB.</p></li>
</ol>
<p><strong>Comparison: Wordfish vs Wordscores (LBG)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Speaker</th>
<th>Wordfish Theta</th>
<th>Wordscores LBG</th>
<th>Consistent?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cowen (FF)</td>
<td>1.77</td>
<td>3.27</td>
<td>✓ Both highest</td>
</tr>
<tr class="even">
<td>Lenihan (FF)</td>
<td>1.82</td>
<td>1.57</td>
<td>✓ Both high</td>
</tr>
<tr class="odd">
<td>Burton (LAB)</td>
<td>-1.10</td>
<td>-0.56</td>
<td>✓ Both opposition</td>
</tr>
<tr class="even">
<td>Kenny (FG)</td>
<td>-0.72</td>
<td>-2.88</td>
<td>✓ Both opposition</td>
</tr>
</tbody>
</table>
<p><strong>Both methods produce similar party orderings</strong> (FF &gt; Green &gt; SF &gt; FG &gt; LAB), validating the results. Wordfish achieves this without pre-defined reference scores, demonstrating the robustness of the political dimension in Irish budget debates.</p>
</section>
<section id="correspondence-analysis" class="level3">
<h3 class="anchored" data-anchor-id="correspondence-analysis">Correspondence Analysis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform corpus to dfm</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>ie_dfm <span class="ot">&lt;-</span> <span class="fu">dfm</span>(<span class="fu">tokens</span>(data_corpus_irishbudget2010))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run correspondence analysis on dfm</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>ca <span class="ot">&lt;-</span> <span class="fu">textmodel_ca</span>(ie_dfm)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot estimated positions and group by party</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="fu">textplot_scale1d</span>(ca, <span class="at">margin =</span> <span class="st">"documents"</span>,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">groups =</span> <span class="fu">docvars</span>(data_corpus_irishbudget2010, <span class="st">"party"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DC_assignment06_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the <strong>estimated political positions</strong> of each speaker using <strong>Correspondence Analysis (CA)</strong>, another unsupervised text scaling method. CA is a multivariate technique that reduces high-dimensional word frequency data to reveal underlying patterns.</p>
<p><strong>What is Correspondence Analysis?</strong></p>
<p>Correspondence Analysis:<br>
- Is an unsupervised dimensionality reduction technique (similar to PCA for categorical data)<br>
- Finds associations between documents and words<br>
- Does not require reference texts or assumptions about word distributions<br>
- Projects documents onto a scale based on word usage patterns</p>
<p><strong>Predicted positions by speaker (Dimension 1)</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Speaker</th>
<th>Party</th>
<th>Dim1</th>
<th>Position</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lenihan, Brian</td>
<td>FF</td>
<td>1.57</td>
<td>Most pro-government</td>
</tr>
<tr class="even">
<td>Cowen, Brian</td>
<td>FF</td>
<td>1.47</td>
<td>Pro-government</td>
</tr>
<tr class="odd">
<td>Gormley, John</td>
<td>Green</td>
<td>0.68</td>
<td>Government (coalition)</td>
</tr>
<tr class="even">
<td>Cuffe, Ciaran</td>
<td>Green</td>
<td>0.14</td>
<td>Near center</td>
</tr>
<tr class="odd">
<td>Ryan, Eamon</td>
<td>Green</td>
<td>-0.19</td>
<td>Near center</td>
</tr>
<tr class="even">
<td>Morgan, Arthur</td>
<td>SF</td>
<td>-0.35</td>
<td>Mild opposition</td>
</tr>
<tr class="odd">
<td>OCaolain, Caoimhghin</td>
<td>SF</td>
<td>-0.37</td>
<td>Mild opposition</td>
</tr>
<tr class="even">
<td>ODonnell, Kieran</td>
<td>FG</td>
<td>-0.62</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td>Gilmore, Eamon</td>
<td>LAB</td>
<td>-0.64</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Bruton, Richard</td>
<td>FG</td>
<td>-0.78</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td>Kenny, Enda</td>
<td>FG</td>
<td>-0.80</td>
<td>Opposition</td>
</tr>
<tr class="even">
<td>Burton, Joan</td>
<td>LAB</td>
<td>-0.96</td>
<td>Strong opposition</td>
</tr>
<tr class="odd">
<td>Quinn, Ruairi</td>
<td>LAB</td>
<td>-1.03</td>
<td>Strong opposition</td>
</tr>
<tr class="even">
<td>Higgins, Michael</td>
<td>LAB</td>
<td>-1.11</td>
<td>Most opposition</td>
</tr>
</tbody>
</table>
<p><strong>Party summary</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 35%">
<col style="width: 26%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Party</th>
<th>Dim1 Range</th>
<th>Average</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>FF (Fianna Fáil)</strong></td>
<td>+1.47 to +1.57</td>
<td>1.52</td>
<td>Government (ruling party)</td>
</tr>
<tr class="even">
<td><strong>Green</strong></td>
<td>-0.19 to +0.68</td>
<td>0.21</td>
<td>Government (coalition partner)</td>
</tr>
<tr class="odd">
<td><strong>SF (Sinn Féin)</strong></td>
<td>-0.37 to -0.35</td>
<td>-0.36</td>
<td>Mild opposition</td>
</tr>
<tr class="even">
<td><strong>FG (Fine Gael)</strong></td>
<td>-0.80 to -0.62</td>
<td>-0.73</td>
<td>Opposition</td>
</tr>
<tr class="odd">
<td><strong>LAB (Labour)</strong></td>
<td>-1.11 to -0.64</td>
<td>-0.93</td>
<td>Opposition (most negative)</td>
</tr>
</tbody>
</table>
<p><strong>Key observations</strong>:</p>
<ol type="1">
<li><p><strong>No confidence intervals</strong>: Unlike Wordscores and Wordfish, CA does not provide uncertainty estimates (no horizontal lines in the plot).</p></li>
<li><p><strong>FF clearly on government side</strong>: Lenihan (1.57) and Cowen (1.47) are positioned furthest right, consistent with their roles as Finance Minister and Taoiseach.</p></li>
<li><p><strong>Green Party variation</strong>:</p>
<ul>
<li>Gormley (0.68) positioned closest to FF among Greens<br>
</li>
<li>Ryan (-0.19) positioned on the opposition side, showing internal party variation</li>
</ul></li>
<li><p><strong>Labour most oppositional</strong>: All Labour members show strongly negative positions, with Higgins (-1.11) being the most extreme, followed by Quinn (-1.03) and Burton (-0.96).</p></li>
<li><p><strong>Sinn Féin near center</strong>: Both SF members cluster around -0.36, more moderate than FG and LAB.</p></li>
</ol>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p><strong>Comparison of three text scaling methods</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Speaker</th>
<th>Wordscores (LBG)</th>
<th>Wordfish</th>
<th>CA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lenihan (FF)</td>
<td>1.57</td>
<td>1.82</td>
<td>1.57</td>
</tr>
<tr class="even">
<td>Cowen (FF)</td>
<td>3.27</td>
<td>1.77</td>
<td>1.47</td>
</tr>
<tr class="odd">
<td>Gormley (Green)</td>
<td>1.03</td>
<td>1.19</td>
<td>0.68</td>
</tr>
<tr class="even">
<td>Burton (LAB)</td>
<td>-0.56</td>
<td>-1.10</td>
<td>-0.96</td>
</tr>
<tr class="odd">
<td>Higgins (LAB)</td>
<td>-0.81</td>
<td>-0.97</td>
<td>-1.11</td>
</tr>
<tr class="even">
<td>Kenny (FG)</td>
<td>-2.88</td>
<td>-0.72</td>
<td>-0.80</td>
</tr>
</tbody>
</table>
<p><strong>Party ordering is consistent across all methods</strong>: FF &gt; Green &gt; SF &gt; FG &gt; LAB</p>
<p><strong>Method comparison</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 31%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Type</th>
<th>Reference Needed</th>
<th>Uncertainty</th>
<th>Key Feature</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wordscores</td>
<td>Supervised</td>
<td>Yes</td>
<td>Yes (SE)</td>
<td>Uses known reference texts</td>
</tr>
<tr class="even">
<td>Wordfish</td>
<td>Unsupervised</td>
<td>No</td>
<td>Yes (SE)</td>
<td>Assumes Poisson distribution</td>
</tr>
<tr class="odd">
<td>CA</td>
<td>Unsupervised</td>
<td>No</td>
<td>No</td>
<td>Dimensionality reduction</td>
</tr>
</tbody>
</table>
<p><strong>Conclusion</strong>: All three methods consistently identify the government-opposition divide in Irish parliamentary debate, validating the robustness of text-based political scaling. The consistent ordering (FF &gt; Green &gt; SF &gt; FG &gt; LAB) across supervised and unsupervised methods demonstrates that political positions are clearly reflected in word usage patterns.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>